---
# install & config cow server

- name: install common python packages
  action: yum pkg={{ item }} state=installed
  with_items:
    - python-setuptools
    - python-pip
  tags:
    - cow
    - python


- name: install supervisor
  action: yum pkg={{ item }} state=installed
  with_items:
    - supervisor
  tags:
    - cow
    - python
    - supervisor

- name: install curl
  action: yum pkg=curl state=installed
  tags:
    - cow

- name: install cow
  raw: export COW_INSTALLDIR=/usr/local/bin/; curl -L git.io/cow | bash
  tags:
    - cow


- name: add cow.conf to supervisor
  template: src=cow.conf.j2 dest=/etc/supervisor/conf.d/cow.conf
  tags:
    - cow
  notify:
    - reload supervisor