---
#install sniproxy

- name: install dep
  apt: pkg={{ item }} state=installed
  with_items:
    - autotools-dev 
    - cdbs 
    - debhelper 
    - dh-autoreconf 
    - dpkg-dev 
    - gettext 
    - libev-dev 
    - libpcre3-dev 
    - libudns-dev 
    - pkg-config
  when: ansible_os_family == "Debian"

- name: install dep
  yum: pkg={{ item }} state=installed
  with_items:
    - autotools-dev
    - cdbs
    - debhelper
    - dh-autoreconf
    - dpkg-dev
    - gettext
    - libev-dev
    - libpcre3-dev
    - libudns-dev
    - pkg-config
  when: ansible_os_family == "RedHat"

- name: clone sniproxy
  git: repo={{ sniproxy_repo }}
       dest=~/sniproxy/

- name: build sniproxy
  shell: ./autogen.sh && ./configure && make && make install
        chdir=~/sniproxy/
        creates=/usr/local/sbin/sniproxy
