---
#install common packages

- name: install editor
  become: yes
  yum: name={{ item }} state=installed
  with_items:
    - vim
  tags:
    - common
    - editor

- name: install version control tools
  become: yes
  yum: name={{ item }} state=installed
  with_items:
    - git
  tags:
    - common
    - vcs

- name: install common python packages
  become: yes
  yum: name={{ item }} state=installed
  with_items:
    - python-setuptools
    - python-pip
    - python-devel
    - python-pycurl
  tags:
    - common
    - python


- name: install supervisor
  become: yes
  yum: name={{ item }} state=installed
  with_items:
    - supervisor
  tags:
    - common
    - python
    - supervisor

- name: install virtualenv
  become: yes
  action: pip name={{ item }} state=present
  with_items:
    - virtualenv
  tags:
    - common
    - python
