---
#setup nginx

- name: install nginx
  action: apt package=nginx state=present
  tags:
    - nginx
  when: ansible_os_family == "Debian"

- name: install nginx
  action: yum package=nginx state=present
  tags:
    - nginx
  when: ansible_os_family == "RedHat"

- name: start nginx
  action: service name=nginx state=started enabled=yes
  tags:
    - nginx

- name: disable default nginx config
  action: file path=/etc/nginx/sites-enabled/default state=absent
  tags: 
    - nginx
  notify:
    - restart nginx
